all:
	mkdir /root/.tmux
	mkdir /root/.tmux/commands
	mkdir /root/.tmux/python
	cp tmux_ssh.py /root/.tmux/python/tmux_ssh.py
	cp split-hssh /root/.tmux/commands/split-hssh
	cp split-vssh /root/.tmux/commands/split-vssh
