All:
	cp ScheduleConfig.py /usr/local/NAS/misc/HAAgent/Config/ScheduleConfig.py
	cp ScheduleConfig.xml /usr/local/NAS/misc/HAAgent/Config/ScheduleConfig.xml
	cp iftcron.py /usr/local/NAS/misc/agent/python/backup/iftcron.py
	cp rsyncAgent.py /usr/local/NAS/misc/agent/python/backup/rsyncAgent.py
	cp schOperation.py /usr/local/NAS/misc/HAAgent/Lib/Backup/schOperation.py
