# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
POWERLINE_SCRIPT=/usr/share/powerline/bindings/bash/powerline.sh
if [ -f $POWERLINE_SCRIPT ]; then
  source $POWERLINE_SCRIPT
fi

alias gs='git status'
alias ga='git add'
alias gb='git branch'
alias gcm='git commit -m'
alias gp='git push'

alias sb="source ~/.bashrc"
alias viba="vim ~/.bashrc"
alias sls="systemctl status"
alias slst="systemctl start"
alias slstop="systemctl stop"
alias gitdiff="git difftool HEAD^"
alias tmux="tmux -2" # -2 Force tmux to assume the terminal supports 256 colours.
