syntax on
set bg=dark
set number
set ts=4
set expandtab
set shiftwidth=4
set cursorline
set autoindent

" enable beep
set novisualbell

" show the matching part of the pair for [] {} and ()
set showmatch
set matchtime=0


execute pathogen#infect()

" syntactic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let python_highlight_all = 1


