all:
	python setup.py /usr/local install --install-purelib=/usr/local/NAS/misc/agent/python/ -f
	python /usr/local/NAS/misc/HAAgent/testHA.py 99 [module_name]Lib

clean:
	rm -rf ./build
	rm -rf files.txt

